version: '3.4'
services:
  message-broker:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - library

networks:
  library: null